"""
    Exam Enrollment Service

    A set of API endpoints that allow you to get information about exam enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_exam_enrollment_sdk
from osis_exam_enrollment_sdk.model.exam_enrollment import ExamEnrollment


class TestExamEnrollment(unittest.TestCase):
    """ExamEnrollment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExamEnrollment(self):
        """Test ExamEnrollment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExamEnrollment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
